version: '3'
services:
  app:
    container_name : node-jwt-chai
    restart: always
    build: .
    ports:
      - '80:4000'
    links: 
      - mongo
      - redis
  mongo:
    container_name : node-jwt-chai-mongo
    image : mongo
    ports: 
      - "27017:27017"
  redis: 
    container_name : node-jwt-chai-redis
    image : redis
    ports: 
      - "6379:6379"